#!/bin/bash
set -euo pipefail
IFS=$' \n\t'
DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

make config=debug -j12
./check
echo "==== build done ===="
bin/Debug-linux-x86_64/digit_recognition/digit_recognition data
