# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  digit_recognition_config = debug
  utils_config = debug
  armadillo_config = debug

else ifeq ($(config),release)
  digit_recognition_config = release
  utils_config = release
  armadillo_config = release

else ifeq ($(config),dist)
  digit_recognition_config = dist
  utils_config = dist
  armadillo_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := digit_recognition utils armadillo

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

digit_recognition: utils armadillo
ifneq (,$(digit_recognition_config))
	@echo "==== Building digit_recognition ($(digit_recognition_config)) ===="
	@${MAKE} --no-print-directory -C digit_recognition -f Makefile config=$(digit_recognition_config)
endif

utils:
ifneq (,$(utils_config))
	@echo "==== Building utils ($(utils_config)) ===="
	@${MAKE} --no-print-directory -C utils -f Makefile config=$(utils_config)
endif

armadillo:
ifneq (,$(armadillo_config))
	@echo "==== Building armadillo ($(armadillo_config)) ===="
	@${MAKE} --no-print-directory -C vendor/armadillo -f Makefile config=$(armadillo_config)
endif

clean:
	@${MAKE} --no-print-directory -C digit_recognition -f Makefile clean
	@${MAKE} --no-print-directory -C utils -f Makefile clean
	@${MAKE} --no-print-directory -C vendor/armadillo -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   digit_recognition"
	@echo "   utils"
	@echo "   armadillo"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"