name: Build Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Ubuntu Clang Debug",
            artifact: "linux_clang_debug.tar.xz",
            build_type: "debug",
            cc: "clang-10",
            cxx: "clang++-10"
          }
          - {
            name: "Ubuntu GCC Debug",
            artifact: "linux_gcc_debug.tar.xz",
            build_type: "debug",
            cc: "gcc-10",
            cxx: "g++-10"
          }
          - {
            name: "Ubuntu Clang Release",
            artifact: "linux_clang_release.tar.xz",
            build_type: "release",
            cc: "clang-10",
            cxx: "clang++-10"
          }
          - {
            name: "Ubuntu GCC Release",
            artifact: "linux_gcc_release.tar.xz",
            build_type: "release",
            cc: "gcc-10",
            cxx: "g++-10"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Update environment
        run: |
          sudo apt update -qq
          sudo apt install -y \
            clang-10 \
            cmake \
            gcc-10 \
            g++-10 \
            libblas-dev \
            liblapack-dev

      - name: Configure CMake
        run: |
          export CC=${{matrix.config.cc}}
          export CXX=${{matrix.config.cxx}}
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}} -j2

      - name: Prepare upload
        run: |
          tar cfz ${{matrix.config.artifact}} build

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{matrix.config.artifact}}
          name: ${{matrix.config.artifact}}
