name: Build Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        config: 
          - {
            name: "Windows MSVC Debug",
            artifact: "windows_msvc_debug.zip",
            cc: "cl",
            cxx: "cl",
            cmake_build_options: "--config Debug",
            cmake_configure_options: '-G "Visual Studio 16 2019" -A x64',
            build_type: "Debug"
          }
          - {
            name: "Windows MSVC Release",
            artifact: "windows-msvc-release.zip",
            cc: "cl",
            cxx: "cl",
            cmake_build_options: "--config Release",
            cmake_configure_options: '-G "Visual Studio 16 2019" -A x64',
            build_type: "Release"
          }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
            submodules: recursive

      - name: Configure CMake
        run: |
          set CC=${{matrix.config.cc}}
          set CXX=${{matrix.config.cxx}}
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.config.build_type}}

      - name: Prepare Upload
        run: |
          7z a -tzip ${{matrix.config.artifact}} build/*

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ${{matrix.config.artifact}}
          name: ${{matrix.config.artifact}}

